NetEase:
  BI_ratios:
  - 0.2
  UB_ratios:
  - 0.0
  UI_ratios:
  - 0.0
  aug_type: Noise
  batch_size_test: 2048
  batch_size_train: 2048
  c_lambdas:
  - 0.05
  c_temps:
  - 0.2
  cagcn_type: jc
  data_path: ./datasets
  ed_interval: 1
  embedding_sizes:
  - 64
  epochs: 50
  fusion_weights:
    BI_layer:
    - 0.4
    - 0.4
    - 0.2
    UB_layer:
    - 0.35
    - 0.15
    - 0.5
    UI_layer:
    - 0.25
    - 0.65
    - 0.1
    modal_weight:
    - 0.5
    - 0.2
    - 0.3
  l2_regs:
  - 1.0e-05
  lrs:
  - 0.001
  neg_num: 1
  num_layerss:
  - 2
  test_interval: 5
  topk:
  - 10
  - 20
  - 40
  - 80
  trend_coeff: 0.06
  trend_mix: true
  trend_norm: row
  trend_topk: 0
  trend_coeff_ub: 0.06
  trend_coeff_ui: 0.06
  trend_coeff_bi: 0.06
  trend_mix_layers: -1
Youshu:
  BI_ratios:
  - 0.1
  UB_ratios:
  - 0.2
  UI_ratios:
  - 0.1
  aug_type: Noise
  batch_size_test: 4096
  batch_size_train: 8192
  c_lambdas:
  - 0.04
  c_temps:
  - 0.23
  cagcn_type: jc
  data_path: ./datasets
  ed_interval: 1
  embedding_sizes:
  - 64
  epochs: 100
  fusion_weights:
    BI_layer:
    - 0.6
    - 0.1
    - 0.3
    UB_layer:
    - 0.7
    - 0.2
    - 0.1
    UI_layer:
    - 0.6
    - 0.2
    - 0.2
    modal_weight:
    - 0.35
    - 0.15
    - 0.5
  l2_regs:
  - 1.0e-05
  lrs:
  - 0.003
  neg_num: 1
  num_layerss:
  - 2
  test_interval: 5
  topk:
  - 10
  - 20
  - 40
  - 80
  trend_coeff: 0.06
iFashion:
  BI_ratios:
  - 0.15
  UB_ratios:
  - 0.05
  UI_ratios:
  - 0.0
  aug_type: Noise
  batch_size_test: 4096
  batch_size_train: 8192
  c_lambdas:
  - 0.1
  c_temps:
  - 0.2
  cagcn_type: jc
  data_path: ./datasets
  ed_interval: 1
  embedding_sizes:
  - 64
  epochs: 50
  fusion_weights:
    BI_layer:
    - 0.5
    - 0.5
    - 0.0
    UB_layer:
    - 0.5
    - 0.5
    - 0.0
    UI_layer:
    - 0.3
    - 0.2
    - 0.5
    modal_weight:
    - 0.1
    - 0.2
    - 0.7
  l2_regs:
  - 1.0e-05
  lrs:
  - 0.003
  neg_num: 1
  num_layerss:
  - 2
  test_interval: 5
  topk:
  - 10
  - 20
  - 40
  - 80
  trend_coeff: 0.06
